# Generated by Django 4.1 on 2022-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_logo", models.CharField(max_length=30)),
                ("skill_heading", models.CharField(max_length=30)),
                ("skill_detail", models.TextField(max_length=30)),
                ("skill_perce", models.CharField(max_length=30)),
            ],
        ),
    ]
