# Generated by Django 4.1 on 2022-09-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("folio2", "0002_project_alter_skills_skill_detail_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="project", new_name="projects",),
    ]
